### ISSUE TITLE
says "DISCORD_TOKEN is not defined in .env file" even tho I pasted the bot token in the file

### ISSUE THREAD

**Issue by Mathematicsss** [sv-du/rbx-manager#52]

**Comment by zachariapopcorn** [comment]
Did you mark it as ``DISCORD_TOKEN=```?

**Comment by Mathematicsss** [comment]
> Did you mark it as `DISCORD_TOKEN=`?

Yes

**Comment by Mathematicsss** [comment]
If you want I can add you on discord and show you the issue while screensharing, seems like it would be easier.

**Comment by zachariapopcorn** [comment]
Make a ticket on my Discord server and I'll help you from there: https://discord.gg/mSc56tNw
