### ISSUE TITLE
DISCORD_TOKEN not defined in .env file

### ISSUE THREAD

**Issue by ThatOneBacon2** [sv-du/rbx-manager#54]
I've done everything right based on the instructions on how to set this up, but I still get this error.

**Comment by sv-du** [comment]
Did you rename ``ENV_FORMAT.txt`` to ``.env``?

**Comment by ThatOneBacon2** [comment]
Yes

**Comment by ThatOneBacon2** [comment]
![image](https://github.com/sv-du/rbx-manager/assets/171447719/b2048ee7-620e-47d1-a225-b53cfc3e26f5)
here's a screenshot of the issue

**Comment by MrBossy** [comment]
You have to rename it to .env not ENV_FORMAT.env as it clearly says.

**Comment by ThatOneBacon2** [comment]
I just realized my mistake, I thought in the instructions told me to change the file type and not change the name.
